config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope :app do
    devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :discussions
    get :proposals, to: 'proposals#index'
    get :opinions, to: 'opinions#index'
    resources :messages, only: :index do
      member do
        patch :mark_as_read
        patch :mark_as_unread
      end
      collection do
        patch :mark_all_as_read
      end
    end
    resources :reactions
    resources :attachments
    resources :canoes do
      member do
        get :history, to: 'canoes#history'
      end
      shallow do
        resources :discussions, except: :index do
          resources :opinions do
            member do
              patch :pin
              patch :unpin
            end
          end
          resources :proposals, except: :index do
            resources :attachments
            member do
              post :in_favor, to: 'votes#in_favor'
              post :opposed, to: 'votes#opposed'
              delete :unvote, to: 'votes#unvote'
            end
          end
        end
        resources :crews
        resources :invitations do
          collection do
            post :accept, to: 'invitations#accept'
          end
        end

        delete 'crews/me', to: 'crews#destroy'
        get 'invite', to: 'canoes#new_invitation'
        post 'invite', to: 'canoes#create_invitation'
      end

      resources :request_to_joins do
        collection do
          post :ask, to: 'request_to_joins#ask'
        end
        member do
          post :accept, to: 'request_to_joins#accept'
        end
      end
    end

    get '/search', to: "search#index"
    get '/search/discussions', to: "search#discussions"
    get '/search/canoes', to: "search#canoes"
  end

  scope :api do
    api version: 1, module: "api/v1", allow_prefix: "v" do
      post 'push', to: 'pages#push'
      get 'system/ping'
      get 'system/last_versions'
      get 'home', to: 'pages#home'
      get 'search/canoes', to: 'search#canoes'
      get 'search/discussions', to: 'search#discussions'
      post 'sessions/facebook', to: 'sessions#facebook'
      get 'users/exist', to: 'users#exist'
      unless Rails.env.production?
        get 'kill_me', to: 'users#kill_me'
      end

      resources :devices, only: [:index, :create]
      resources :messages, only: :index do
        collection do
          get 'unreads_count'
          post 'mark_all_as_read'
        end
        member do
          post 'mark_as_read'
          post 'mark_as_unread'
        end
      end
      resources :canoes, only: [:show] do
        member do
          delete 'crews/me', to: 'crews#destroy_me'
          delete 'request_to_joins', to: 'request_to_joins#destroy_by_canoe'
        end
        shallow do
          resources :discussions, except: :destroy do
            get 'decision_histories', on: :member
            resources :opinions
            resources :proposals do
              member do
                post :in_favor, to: 'votes#in_favor'
                post :opposed, to: 'votes#opposed'
                delete :unvote, to: 'votes#unvote'
              end
            end
          end
          resources :request_to_joins, only: [:create, :destroy] do
            patch :accept, on: :member
          end
          resources :invitations, only: [:create, :destroy]
        end
      end
    end
  end

  get '/:slug/discussions/:sequential_id', to: "discussions#short", as: 'short_discussion'
  get '/:slug', to: "canoes#short", as: 'short_canoe'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < Api::V1::BaseController
  def index
    paginated current_user.mailbox.notifications.page(params[:page]).map{ |n| hashed_notification(n) }
  end

  def unreads_count
    expose current_user.mailbox.notifications.unread.count
  end

  def mark_as_read
    mark_as(:read)
  end

  def mark_as_unread
    mark_as(:unread)
  end

  def mark_all_as_read
    Mailboxer::Receipt.notifications_receipts.recipient(current_user).mark_as_read
    head :ok
  end

  private

  def mark_as(read_or_unread)
    @notification = current_user.mailbox.notifications.find params[:id]
    if read_or_unread == :read
      @notification.mark_as_read(current_user)
    else
      @notification.mark_as_unread(current_user)
    end
    expose hashed_notification(@notification)
  end

  def hashed_notification(notification)
    notification.serializable_hash.update(is_read: notification.is_read?(current_user))
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @unread_count = current_user.mailbox.notifications.unread.count
    @notifications = current_user.mailbox.notifications.page params[:page]
  end

  def mark_as_read
    mark_as(:read)
  end

  def mark_as_unread
    mark_as(:unread)
  end

  def mark_all_as_read
    Mailboxer::Receipt.notifications_receipts.recipient(current_user).mark_as_read

    respond_to do |format|
      format.html { redirect_to :index }
      format.js
    end
  end

  def mark_as(read_or_unread)
    @notification = current_user.mailbox.notifications.find params[:id]
    if read_or_unread == :read
      @notification.mark_as_read(current_user)
    else
      @notification.mark_as_unread(current_user)
    end
    @has_unread = current_user.mailbox.notifications.unread.any?
    respond_to do |format|
      format.html { redirect_to :index }
      format.js { render(template: "messages/mark_as") }
    end
  end
end

app/views/messages/index.html.haml
.bs-component
  .container
    .panel.panel-default
      %table.table.table-bordered
        %tbody
          %tr.active
            %td
              %h4.text-muted
                %i.fa.fa-inbox
                최근
                - if @unread_count > 0
                  %strong= @unread_count
                  개의 읽지 않은 알림이 있습니다.
                - else
                  모든 알림을 다 읽었습니다!
            %td.text-center(style='width: 40px; vertical-align: middle')
              %span.read-check-all(style="#{'display: none' if @unread_count > 0}")
                %i.fa.fa-square-o(data-toggle='tooltip' data-placement='bottom' title='모두 읽었습니다')
              = link_to mark_all_as_read_messages_path, method: :patch, remote: true, style: "#{'display: none' if @unread_count <= 0}", class: 'unread-check-all' do
                %i.fa.fa-check-square-o(data-toggle='tooltip' data-placement='bottom' title='모두 읽은 것으로 표시합니다')
          - @notifications.each do |notification|
            - tr_class = notification.is_read?(current_user) ? '' : 'alert-unread'
            %tr[notification]{ class: tr_class }
              %td
                %p.text-muted
                  %i.fa.fa-clock-o
                  = date_f notification.created_at
                %p= simple_format notification.body
              %td.text-center(style='width: 40px;')
                = link_to mark_as_unread_message_path(notification), method: :patch, remote: true, style: "#{'display: none' if notification.is_unread?(current_user)}", class: 'read-check' do
                  %i.fa.fa-square-o(data-toggle='tooltip' data-placement='bottom' title='읽지않은 것으로 표시합니다')
                = link_to mark_as_read_message_path(notification), method: :patch, remote: true, style: "#{'display: none' if notification.is_read?(current_user)}", class: 'unread-check' do
                  %i.fa.fa-check-square-o(data-toggle='tooltip' data-placement='bottom' title='읽은 것으로 표시합니다')

    .text-center= paginate @notifications, theme: 'twitter-bootstrap-3'

app/views/messages/mark_all_as_read.js.haml
$('.read-check').show();
$('.unread-check').hide();
$('.alert-unread').removeClass('alert-unread');
$('.read-check-all').show();
$('.unread-check-all').hide();

app/views/messages/mark_as.js.haml
- if @notification.is_read?(current_user)
  $('##{dom_id(@notification)} .read-check').show();
  $('##{dom_id(@notification)} .unread-check').hide();
  $('##{dom_id(@notification)}').removeClass('alert-unread');
- else
  $('##{dom_id(@notification)} .read-check').hide();
  $('##{dom_id(@notification)} .unread-check').show();
  $('##{dom_id(@notification)}').addClass('alert-unread');

- if @has_unread
  $('.read-check-all').hide();
  $('.unread-check-all').show();
- else
  $('.read-check-all').show();
  $('.unread-check-all').hide();

"#{current_user.mailbox.notifications.unread.inspect}";