config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope :app do
    devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :discussions
    get :proposals, to: 'proposals#index'
    get :opinions, to: 'opinions#index'
    resources :messages, only: :index do
      member do
        patch :mark_as_read
        patch :mark_as_unread
      end
      collection do
        patch :mark_all_as_read
      end
    end
    resources :reactions
    resources :attachments
    resources :canoes do
      member do
        get :history, to: 'canoes#history'
      end
      shallow do
        resources :discussions, except: :index do
          resources :opinions do
            member do
              patch :pin
              patch :unpin
            end
          end
          resources :proposals, except: :index do
            resources :attachments
            member do
              post :in_favor, to: 'votes#in_favor'
              post :opposed, to: 'votes#opposed'
              delete :unvote, to: 'votes#unvote'
            end
          end
        end
        resources :crews
        resources :invitations do
          collection do
            post :accept, to: 'invitations#accept'
          end
        end

        delete 'crews/me', to: 'crews#destroy'
        get 'invite', to: 'canoes#new_invitation'
        post 'invite', to: 'canoes#create_invitation'
      end

      resources :request_to_joins do
        collection do
          post :ask, to: 'request_to_joins#ask'
        end
        member do
          post :accept, to: 'request_to_joins#accept'
        end
      end
    end

    get '/search', to: "search#index"
    get '/search/discussions', to: "search#discussions"
    get '/search/canoes', to: "search#canoes"
  end

  scope :api do
    api version: 1, module: "api/v1", allow_prefix: "v" do
      post 'push', to: 'pages#push'
      get 'system/ping'
      get 'system/last_versions'
      get 'home', to: 'pages#home'
      get 'search/canoes', to: 'search#canoes'
      get 'search/discussions', to: 'search#discussions'
      post 'sessions/facebook', to: 'sessions#facebook'
      get 'users/exist', to: 'users#exist'
      unless Rails.env.production?
        get 'kill_me', to: 'users#kill_me'
      end

      resources :devices, only: [:index, :create]
      resources :messages, only: :index do
        collection do
          get 'unreads_count'
          post 'mark_all_as_read'
        end
        member do
          post 'mark_as_read'
          post 'mark_as_unread'
        end
      end
      resources :canoes, only: [:show] do
        member do
          delete 'crews/me', to: 'crews#destroy_me'
          delete 'request_to_joins', to: 'request_to_joins#destroy_by_canoe'
        end
        shallow do
          resources :discussions, except: :destroy do
            get 'decision_histories', on: :member
            resources :opinions
            resources :proposals do
              member do
                post :in_favor, to: 'votes#in_favor'
                post :opposed, to: 'votes#opposed'
                delete :unvote, to: 'votes#unvote'
              end
            end
          end
          resources :request_to_joins, only: [:create, :destroy] do
            patch :accept, on: :member
          end
          resources :invitations, only: [:create, :destroy]
        end
      end
    end
  end

  get '/:slug/discussions/:sequential_id', to: "discussions#short", as: 'short_discussion'
  get '/:slug', to: "canoes#short", as: 'short_canoe'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  include PublicActivity::Model
  include CanoeTimestampable

  acts_as_paranoid
  acts_as_sequenced scope: :canoe_id
  acts_as_readable on: :discussed_at

  belongs_to :user
  belongs_to :canoe, counter_cache: true
  has_many :opinions
  has_many :proposals do
    def top_of_votes_count(choice)
      top_of_count = self.max_votes_count(choice)
      top_of_count = -1 if top_of_count == 0
      top_of_count
    end

    def max_votes_count(choice)
      self.maximum("#{choice}_votes_count")
    end
  end
  has_many :attachments, as: :attachable

  validates :canoe, presence: true

  attr_accessor :current_activity_user
  cattr_accessor :skip_callbacks
  before_create :init_discussed_at, unless: :skip_callbacks

  scope :valid_parent, -> { joins(:canoe) }
  scope :persisted, -> { where "id IS NOT NULL" }
  scoped_search on: %w(subject decision)
  scoped_search in: :opinions, on: %w(body)
  scoped_search in: :proposals, on: %w(body)
  accepts_nested_attributes_for :opinions

  def init_discussed_at
    self.discussed_at = DateTime.now
    user.touch(:home_visited_at)
  end

  def discussion
    self
  end

  def activities_merged
    Hash[activities.order(created_at: :asc)
      .slice_when{ |a, b| !meargable_in_timeline?(a, b) }
      .map { |chunk| [chunk.first, zip_activities(chunk)] }]
  end

  def matched_newest_proposal(q)
    newest_proposal = proposals.search_for(q).newest
  end

  def matched_newest_opinion(q)
    newest_opinion = opinions.search_for(q).newest
  end

  def newest_proposal_or_opinion(q = nil)
    if q.present?
      newest_proposal = proposals.search_for(q).newest
      newest_opinion = opinions.search_for(q).newest
    else
      newest_proposal = proposals.newest
      newest_opinion = opinions.newest
    end

    return newest_opinion if newest_proposal.nil?
    return newest_proposal if newest_opinion.nil?
    (newest_proposal.created_at > newest_opinion.created_at) ? newest_proposal : newest_opinion
  end

  def updated_decision?
    activities.today.where(key: 'discussion.decision', task: 'update').any?
  end

  def timestamp_user
    current_activity_user
  end

  def newest_opinion
    opinions.newest
  end

  def newest_proposal
    proposals.newest
  end

  private

  def meargable_in_timeline?(m, n)
    return false if (m.key == 'opinion' or n.key == 'opinion')
    return false if m.owner != n.owner

    if TimeDifference.between(m.created_at, n.created_at).in_minutes.abs <= 5
      return true
    end
    if !m.created_at.today? and m.created_at.to_date == n.created_at.to_date
      return true
    end

    return false
  end

  def zip_activities(chunk)
    chunk.group_by(&:subject).map do |subject, activities|
      result = activities.sort_by(&:created_at)

      vote_activities = result.select{ |a| a.measure_type == Vote.to_s }
      if (vote_activities.count > 2)
        if vote_activities.first.task == vote_activities.last.task
          result -= vote_activities[1..-1]
        else
          result -= vote_activities[1...-1]
        end
      end

      proposal_update_activities = result.select{ |a| a.key == 'proposal' and a.task == 'update' }
      result -= proposal_update_activities[0...-1] if (proposal_update_activities.count > 1)

      discussion_decision_update_activities = result.select{ |a| a.key == 'discussion.decision' and a.task == 'update' }
      result -= discussion_decision_update_activities[0...-1] if (discussion_decision_update_activities.count > 1)

      {subject: subject, activities: result}
    end
  end
end

app/controllers/api/v1/discussions_controller.rb
class Api::V1::DiscussionsController < Api::V1::BaseController
  include DiscussionActivityTraking

  def create
    @canoe = Canoe.find params[:canoe_id]

    assert_crew!

    @discussion = @canoe.discussions.build(create_params)
    @discussion.user = current_user
    @discussion.current_activity_user = current_user

    @opinion = @discussion.opinions.first
    if @opinion.present?
      if @opinion.body.blank?
        @discussion.opinions.destroy @opinion
      else
        @opinion.user = current_user
      end
    end
    if @discussion.save
      push_to_client(@discussion)
      create_opinions_create_activty(@discussion.opinions.first) if @discussion.opinions.first.present?
      expose @discussion
    else
      error!(:invalid_resource, @discussion.errors)
    end
  end

  def show
    @discussion = Discussion.find params[:id]
    @canoe = @discussion.canoe

    assert_canoe!

    if user_signed_in?
      @discussion.mark_as_read! :for => current_user
    end

    expose hashed_detail_discussion(@discussion)
  end

  def decision_histories
    @discussion = Discussion.find params[:id]
    @canoe = @discussion.canoe

    assert_canoe!

    collection @discussion.activities.where('key': 'discussion.decision').order(created_at: :desc).select { |p| p.parameters.present? }, include: [:owner]
  end

  def update
    @discussion = Discussion.find params[:id]
    @canoe = @discussion.canoe

    assert_crew!

    @discussion.current_activity_user = current_user

    if @discussion.update_attributes(update_params)
      push_to_client(@discussion)
      create_discussions_update_decision_activty(@discussion) if @discussion.previous_changes['decision'].present?
      expose @discussion
    else
      error!(:invalid_resource, @discussion.errors)
    end
  end

  private

  def create_params
    params.require(:discussion).permit(:subject, opinions_attributes: [ :body ])
  end

  def update_params
    params.require(:discussion).permit(:subject, :decision)
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  include SlackPushing
  include Messaging
  include DiscussionActivityTraking

  before_filter :authenticate_user!, except: [:show, :short]
  load_and_authorize_resource :canoe
  load_and_authorize_resource :discussion, through: :canoe, shallow: true

  def show
    redirect_to short_discussion_path(@discussion.canoe.slug, @discussion.sequential_id)
  end

  def short
    @canoe = Canoe.find_by slug: params[:slug]
    @discussion = @canoe.discussions.find_by sequential_id: params[:sequential_id]

    if user_signed_in?
      @discussion.mark_as_read! :for => current_user
    end
    render_404 and return if @discussion.nil?
    @canoe = @discussion.canoe
    render_404 and return if @canoe.nil?

    meta_description = "#{@canoe.title} 카누에서 의견을 교환하고 있습니다."
    meta_description = "현재 결정 사항은 \"#{@discussion.decision}\" 입니다." if @discussion.decision.present?

    prepare_meta_tags title: @discussion.subject,
                      description: meta_description
    prepare_meta_tags image: @canoe.cover if @canoe.cover.present?

    render template: 'discussions/show'
  end

  def new
  end

  def edit
  end

  def create
    @discussion.user = current_user
    @discussion.current_activity_user = current_user

    @opinion = @discussion.opinions.first
    if @opinion.present?
      if @opinion.body.blank?
        @discussion.opinions.destroy @opinion
      else
        @opinion.user = current_user if @opinion.present?
      end
    end
    if @discussion.save
      push_to_slack(@discussion)
      create_opinions_create_activty(@discussion.opinions.first) if @discussion.opinions.first.present?
      redirect_to @discussion
    else
      render 'new'
    end
  end

  def update
    @discussion.current_activity_user = current_user

    if @discussion.update_attributes(update_params)
      push_to_slack(@discussion)
      create_discussions_update_decision_activty(@discussion) if @discussion.previous_changes['decision'].present?
      redirect_to @discussion
    else
      render 'edit'
    end
  end

  def destroy
    @discussion.destroy
    notify_to_crews(@discussion)
    push_to_slack(@discussion)
    redirect_to @discussion.canoe
  end

  private

  def create_params
    params.require(:discussion).permit(:subject, :canoe_id, opinions_attributes: [ :body ])
  end

  def update_params
    params.require(:discussion).permit(:subject, :body, :decision)
  end
end

app/views/discussions/_decision.html.haml
#discussion__decision.clearfix(style='margin: 20px 0;')
  .clearfix
    .canoe-toggle-item
      %div.discussion__decision__body(style='margin-bottom: 20px')
        %strong
          - if @discussion.decision.present?
            = smart_body(@discussion.decision, {data: { toggle: 'preview', 'embed-stage': "#discussion__decision .decision__body--embeded", 'image-stage': "#discussion__decision .attachments--image" } })
            .decision__body--embeded
          - if @discussion.decision.blank?
            아직 결정된 사항이 없습니다.
    - if can? :update, @discussion
      .canoe-toggle-item.hidden
        = form_for @discussion do |f|
          .form-group
            = f.text_area :decision, placeholder: '모두 볼 수 있도록 현재까지 결정한 사항을 적어주세요', autofocus: true, class: 'form-control'
          .form-group.pull-right
            %a.text-muted(role="button" data-toggle="canoe-toggle" href="#" data-parent="#discussion__decision" style="margin-right: 20px;") 취소
            = f.submit '저장하기', class: 'btn btn-primary'
  = render partial: 'attachments/collection', locals: { attachable: @discussion }

app/views/discussions/_discussion.html.haml
- unread = user_signed_in? && discussion.unread?(current_user)
- tr_class = unread ? 'alert-unread' : ''
%li.list-group-item(style='padding: 0;')
  %div[discussion]{ class: tr_class }
    %div(style='padding: 10px;')
      - if local_assigns[:show_canoe]
        %small
          = link_to canoe_home_path(discussion.canoe) do
            = image_tag discussion.canoe.logo_url, style: 'width: 13px; height: 13px; margin-right: 1px; border: 1px solid #efefef;'
            = discussion.canoe.title
      %h4
        %span.label.label-default(style='padding: 0 0.3em; background-color:rgba(153, 153, 153, 0.4);')= discussion.sequential_id
        = link_to discussion_home_path(discussion) do
          = highlight(discussion.subject, params[:q])
        %small
          %span
            %i.fa.fa-comments
            = discussion.opinions.count
          %span
            %i.fa.fa-rocket
            = discussion.proposals.count
      - if discussion.decision.present?
        .discussion__decision__body
          %i.fa.fa-thumb-tack
          - if discussion.updated_decision?
            %span.label.label-default 업데이트
          = highlight(truncate(discussion.decision, length: 70), params[:q])
    - item = discussion.newest_proposal_or_opinion(params[:q])
    - if item.present?
      %div(style='background-color: #f5f5f5; font-size: 85%;')
        .media(style='padding: 20px; background-color: #fafafa;')
          .media-left.media-top
            = user_byline item.user, true
          .media-body
            .media-head.text-muted
              = item.user.nickname
              %i.fa.fa-clock-o
              = date_f item.created_at
            .discussion__newest_proposal_or_opinion__body
              - if item.is_a?(Proposal)
                %strong(style='margin-right: 5px')
                  제안
                  %span.label.label-default>
                    = item.sequential_id
              = highlight(smart_body(item.body, nil, wrapper_tag: 'span'), params[:q])
              %span(style='margin-left: 1em;')

app/views/discussions/_form.html.haml
= form_for (@discussion.new_record? ? [@discussion.canoe, @discussion] : @discussion) do |f|
  - if @discussion.canoe.nil?
    .form-group
      = f.label :canoe_id
      = f.collection_select :canoe_id, current_user.joined_canoes, :id, :title, {prompt: '카누를 선택해 주세요'}, {class: 'form-control'}
  .form-group
    = f.label :subject
    = f.text_field :subject, class: 'form-control'
  - if @discussion.new_record?
    = f.fields_for :opinions, @discussion.opinions.build do |f_opinion|
      .form-group
        = f_opinion.label :body
        = f_opinion.text_area :body, class: 'form-control'
  = f.submit '저장', class: 'btn btn-default'

app/views/discussions/edit.html.haml
.container
  %h3 논의 수정
  = render 'form'

app/views/discussions/new.html.haml
.container
  %h3 논의 생성
  = render 'form'

app/views/discussions/show.html.haml
= render 'canoes/canoe_header'

.bs-component
  .container
    .clearfix
      .pull-right
        = user_byline @discussion.user
        %i.fa.fa-clock-o
        = date_f @discussion.created_at
        - if can? :update, @discussion
          = link_to [:edit, @discussion] do
            %i.fa.fa-edit
        - if can? :destroy, @discussion
          = link_to @discussion, method: :delete, data: { confirm: '정말 삭제하시겠습니까?'} do
            %i.fa.fa-trash
      .text-muted
        논의
        %span.label.label-default(style='background-color:rgba(153, 153, 153, 0.4);')= @discussion.sequential_id
    %h2.text-center(style='margin-bottom:50px;')
      #{@discussion.subject}

    %h4
      %i.fa.fa-thumb-tack
      현재 결정 사항
      - if can? :update, @discussion
        %button.btn-link(role="button" data-toggle="canoe-toggle" data-parent="#discussion__decision" data-focus="#discussion_decision")
          %i.fa.fa-edit
      %button.btn-link
        = render partial: 'attachments/button', locals: { attachable: @discussion }

    = render 'decision'

    %h4
      %ul.nav.nav-tabs
        %li.text-center(role="presentation" class="active" style='width: 50%')
          %a#opinions-tab(href="#opinions" role="tab" data-toggle="tab")
            %i.fa.fa-comments
            의견
        %li.text-center(role="presentation" style='width: 50%')
          %a#proposals-tab(href="#proposals" role="tab" data-toggle="tab")
            %i.fa.fa-rocket
            제안
            - if @discussion.proposals.count != 0
              %span.badge= @discussion.proposals.count
    .tab-content(style='margin-top: 20px;')
      .tab-pane.active#opinions(role="tabpanel")
        %ul.media-list
          = render partial: 'public_activity/collection', locals: { discussion: @discussion }
          - if can? :update, @discussion
            %li.media.timeline.timeline-opinion
              .media-left
                %a{:href => "#"}
                  = image_tag current_user.image_url, class: 'media-object img-circle', style: 'width:64px;height:64px;'
              .media-body
                = form_for [@discussion, Opinion.new] do |f|
                  .form-group
                    = f.text_area :body, class: 'form-control', style: "width: 100%; height: 100px; border-bottom-right-radius: 0; border-bottom-left-radius: 0;", placeholder: '내 의견은...'
                    .clearfix(style="background-color: #efefef; border: 1px solid #ccc; border-top: none; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; padding: 10px 0;")
                      .pull-left.text-center(style='width: 10%')
                        %button.btn-file.btn-link
                          = f.fields_for 'attachments_attributes[]', f.object.attachments.build do |f_attachment|
                            = f_attachment.file_field :source, data: {list: '#opinions__files'}
                          %i.fa.fa-upload.text-muted
                      %ul.pull-left.list-inline#opinions__files(style='margin-bottom: 0; margin-left: 0; width: 90%;')
                  .form-group.pull-right
                    = f.submit '의견올리기', class: 'btn btn-default'

      .tab-pane#proposals.clearfix(role="tabpanel" style='margin: 20px 0;')
        - if @discussion.proposals.any?
          %ul.list-group
            - @discussion.proposals.order_by_in_favor_votes_count.latest.each do |proposals|
              = render proposals
        - else
          %strong
            아직 제안이 없습니다.
        - if can? :update, @discussion
          = form_for [@discussion, @discussion.proposals.build] do |f|
            .form-group
              = f.text_area :body, class: 'form-control', style: "width: 100%; height: 60px; border-bottom-right-radius: 0; border-bottom-left-radius: 0;", placeholder: '내 제안은...'
              .clearfix(style="background-color: #efefef; border: 1px solid #ccc; border-top: none; border-bottom-right-radius: 4px; border-bottom-left-radius: 4px; padding: 10px 0;")
                .pull-left.text-center(style='width: 10%')
                  %button.btn-file.btn-link
                    = f.fields_for 'attachments_attributes[]', f.object.attachments.build do |f_attachment|
                      = f_attachment.file_field :source, data: {list: '#proposals__files'}
                    %i.fa.fa-upload.text-muted
                %ul.pull-left.list-inline#proposals__files(style='margin-bottom: 0; margin-left: 0; width: 90%;')
            .form-group.text-right
              = f.submit '제안올리기', class: 'btn btn-default'