config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope :app do
    devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :discussions
    get :proposals, to: 'proposals#index'
    get :opinions, to: 'opinions#index'
    resources :messages, only: :index do
      member do
        patch :mark_as_read
        patch :mark_as_unread
      end
      collection do
        patch :mark_all_as_read
      end
    end
    resources :reactions
    resources :attachments
    resources :canoes do
      member do
        get :history, to: 'canoes#history'
      end
      shallow do
        resources :discussions, except: :index do
          resources :opinions do
            member do
              patch :pin
              patch :unpin
            end
          end
          resources :proposals, except: :index do
            resources :attachments
            member do
              post :in_favor, to: 'votes#in_favor'
              post :opposed, to: 'votes#opposed'
              delete :unvote, to: 'votes#unvote'
            end
          end
        end
        resources :crews
        resources :invitations do
          collection do
            post :accept, to: 'invitations#accept'
          end
        end

        delete 'crews/me', to: 'crews#destroy'
        get 'invite', to: 'canoes#new_invitation'
        post 'invite', to: 'canoes#create_invitation'
      end

      resources :request_to_joins do
        collection do
          post :ask, to: 'request_to_joins#ask'
        end
        member do
          post :accept, to: 'request_to_joins#accept'
        end
      end
    end

    get '/search', to: "search#index"
    get '/search/discussions', to: "search#discussions"
    get '/search/canoes', to: "search#canoes"
  end

  scope :api do
    api version: 1, module: "api/v1", allow_prefix: "v" do
      post 'push', to: 'pages#push'
      get 'system/ping'
      get 'system/last_versions'
      get 'home', to: 'pages#home'
      get 'search/canoes', to: 'search#canoes'
      get 'search/discussions', to: 'search#discussions'
      post 'sessions/facebook', to: 'sessions#facebook'
      get 'users/exist', to: 'users#exist'
      unless Rails.env.production?
        get 'kill_me', to: 'users#kill_me'
      end

      resources :devices, only: [:index, :create]
      resources :messages, only: :index do
        collection do
          get 'unreads_count'
          post 'mark_all_as_read'
        end
        member do
          post 'mark_as_read'
          post 'mark_as_unread'
        end
      end
      resources :canoes, only: [:show] do
        member do
          delete 'crews/me', to: 'crews#destroy_me'
          delete 'request_to_joins', to: 'request_to_joins#destroy_by_canoe'
        end
        shallow do
          resources :discussions, except: :destroy do
            get 'decision_histories', on: :member
            resources :opinions
            resources :proposals do
              member do
                post :in_favor, to: 'votes#in_favor'
                post :opposed, to: 'votes#opposed'
                delete :unvote, to: 'votes#unvote'
              end
            end
          end
          resources :request_to_joins, only: [:create, :destroy] do
            patch :accept, on: :member
          end
          resources :invitations, only: [:create, :destroy]
        end
      end
    end
  end

  get '/:slug/discussions/:sequential_id', to: "discussions#short", as: 'short_discussion'
  get '/:slug', to: "canoes#short", as: 'short_canoe'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end
end

app/controllers/api/v1/search_controller.rb
class Api::V1::SearchController < Api::V1::BaseController
  def discussions
    query = params.require(:q)
    @all = (params[:all] || 'false') == 'true'
    if @all
      @discussions = Discussion.valid_parent.order(discussed_at: :desc).search_for(query)
    else
      @discussions = current_user.joined_discussions.order(discussed_at: :desc).search_for(query)
    end
    @discussions = @discussions.page(params[:page])
    expose @discussions.map { |discussion| hashed_searched_discussion(discussion, query) },
      metadata: hashed_page_meta(@discussions).update(canoes_count: Canoe.search_for(query).count)
  end

  def canoes
    query = params.require(:q)
    @canoes = Canoe.search_for(query).page(params[:page])
    expose @canoes.map { |canoe| hashed_basic_canoe(canoe) }, metadata: hashed_page_meta(@canoes).update(
      all_discussions_count: Discussion.valid_parent.order(discussed_at: :desc).search_for(query).count,
      discussions_count: current_user.joined_discussions.search_for(query).count
    )
  end

  private

  def hashed_searched_discussion(discussion, query)
    discussion.serializable_hash(include: {
      user: {}
    }).update(
      canoe: hashed_basic_canoe(discussion.canoe),
      matched_proposal: hashed_matched_proposal(discussion, query),
      matched_opinion: hashed_matched_opinion(discussion, query)
    )
  end

  def hashed_matched_proposal(discussion, query)
    result = discussion.matched_newest_proposal(query)
    result.blank? ? nil : result.serializable_hash(include: [:user])
  end

  def hashed_matched_opinion(discussion, query)
    result = discussion.matched_newest_opinion(query)
    result.blank? ? nil : result.serializable_hash(include: [:user])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def discussions
    query = params[:q]
    @all = (params[:all] || 'false') == 'true'
    @all = true unless user_signed_in?
    if query.present?
      if @all
        @discussions = Discussion.valid_parent.order(discussed_at: :desc).search_for(query)
      else
        @discussions = current_user.joined_discussions.order(discussed_at: :desc).search_for(query)
      end
      @discussions_count = @discussions.count
      @discussions_on_current_page = @discussions.page(params[:page])
    end
  end

  def canoes
    query = params[:q]
    if query.present?
      @canoes = Canoe.search_for(query)
      @canoes_count = @canoes.count
      @canoes_on_current_page = @canoes.page(params[:page])
    end
  end
end

app/views/search/_canoes_form.html.haml
.page-header
  %h3(style='margin-right: 15px;')
    %i.fa.fa-cubes
    카누검색
%div(style='margin: 10px 0')
  = form_tag search_canoes_path, method: :get, class: 'form-inline', style: 'display: inline-block;' do
    .form-group(style='display: inline-block')
      = text_field_tag :q, params[:q], class: 'form-control'
    = submit_tag '찾기', class: 'btn btn-default', style: 'margin-right: 2em;'

app/views/search/_discussions_form.html.haml
.page-header
  %h3(style='margin-right: 15px;')
    %i.fa.fa-comments
    논의검색
%div(style='margin: 10px 0')
  = form_tag search_discussions_path, method: :get, class: 'form-inline', style: 'display: inline-block;' do
    .form-group(style='display: inline-block')
      = text_field_tag :q, params[:q], class: 'form-control'
    = submit_tag '찾기', class: 'btn btn-default', style: 'margin-right: 2em;'
    - if user_signed_in?
      .form-group(style='display: inline-block')
        %label
          = check_box_tag :all, 'true', @all
          %small 모든 카누에서 검색합니다.
    - else
      = hidden_field_tag :all, 'true'

app/views/search/canoes.html.haml
.bs-component
  .container
    %h4
      %ul.nav.nav-tabs
        %li.text-center(role="presentation" style='width: 50%')
          = link_to search_discussions_path(q: params[:q]) do
            %i.fa.fa-flag
            - if user_signed_in?
              내
            - else
              모든
            논의
        %li.text-center(role="presentation" class="active" style='width: 50%')
          %a(href='#')
            %i.fa.fa-cubes
            카누

    - if params[:q].present?
      %p.text-muted 검색 결과  #{@canoes_count}건

      - if @canoes_on_current_page.any?
        .row
          - @canoes_on_current_page.each do |canoe|
            .col-sm-4.col-xs-6
              = render canoe
        .row
          .col-xs-12.text-center
            = paginate @canoes_on_current_page, theme: 'twitter-bootstrap-3'

app/views/search/discussions.html.haml
.bs-component
  .container
    %h4
      %ul.nav.nav-tabs
        %li.text-center(role="presentation" class="active" style='width: 50%')
          %a(href='#')
            %i.fa.fa-flag
            - if @all
              모든
            - else
              내
            논의
        %li.text-center(role="presentation" style='width: 50%')
          = link_to search_canoes_path(q: params[:q]) do
            %i.fa.fa-cubes
            카누

    - if params[:q].present?
      %p
        - if @all
          - if user_signed_in?
            .pull-right
              = link_to search_discussions_path(q: params[:q], all: 'false') do
                내 카누 논의에서만
                %i.fa.fa-arrow-right
        - else
          .pull-right
            = link_to search_discussions_path(q: params[:q], all: 'true') do
              모든 카누 논의에서
              %i.fa.fa-arrow-right
        %span.text-muted 검색 결과 #{@discussions_count}건
      - if @discussions_on_current_page.any?
        .row
          .col-xs-12
            .panel.panel-default
              %ul.list-group
                - @discussions_on_current_page.each do |discussion|
                  = render discussion, { show_canoe: true }
        .row
          .col-xs-12.text-center
            = paginate @discussions_on_current_page, theme: 'twitter-bootstrap-3'

app/views/search/index.html.haml
.bs-component
  .container
    %h4
      %ul.nav.nav-tabs
        %li.text-center(role="presentation" class="active" style='width: 50%')
          %a(href='#')
            %i.fa.fa-flag
            - if user_signed_in?
              내
            - else
              모든
            논의
        %li.text-center(role="presentation" style='width: 50%')
          = link_to search_canoes_path(q: params[:q]) do
            %i.fa.fa-cubes
            카누