config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  scope :app do
    devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
    resources :discussions
    get :proposals, to: 'proposals#index'
    get :opinions, to: 'opinions#index'
    resources :messages, only: :index do
      member do
        patch :mark_as_read
        patch :mark_as_unread
      end
      collection do
        patch :mark_all_as_read
      end
    end
    resources :reactions
    resources :attachments
    resources :canoes do
      member do
        get :history, to: 'canoes#history'
      end
      shallow do
        resources :discussions, except: :index do
          resources :opinions do
            member do
              patch :pin
              patch :unpin
            end
          end
          resources :proposals, except: :index do
            resources :attachments
            member do
              post :in_favor, to: 'votes#in_favor'
              post :opposed, to: 'votes#opposed'
              delete :unvote, to: 'votes#unvote'
            end
          end
        end
        resources :crews
        resources :invitations do
          collection do
            post :accept, to: 'invitations#accept'
          end
        end

        delete 'crews/me', to: 'crews#destroy'
        get 'invite', to: 'canoes#new_invitation'
        post 'invite', to: 'canoes#create_invitation'
      end

      resources :request_to_joins do
        collection do
          post :ask, to: 'request_to_joins#ask'
        end
        member do
          post :accept, to: 'request_to_joins#accept'
        end
      end
    end

    get '/search', to: "search#index"
    get '/search/discussions', to: "search#discussions"
    get '/search/canoes', to: "search#canoes"
  end

  scope :api do
    api version: 1, module: "api/v1", allow_prefix: "v" do
      post 'push', to: 'pages#push'
      get 'system/ping'
      get 'system/last_versions'
      get 'home', to: 'pages#home'
      get 'search/canoes', to: 'search#canoes'
      get 'search/discussions', to: 'search#discussions'
      post 'sessions/facebook', to: 'sessions#facebook'
      get 'users/exist', to: 'users#exist'
      unless Rails.env.production?
        get 'kill_me', to: 'users#kill_me'
      end

      resources :devices, only: [:index, :create]
      resources :messages, only: :index do
        collection do
          get 'unreads_count'
          post 'mark_all_as_read'
        end
        member do
          post 'mark_as_read'
          post 'mark_as_unread'
        end
      end
      resources :canoes, only: [:show] do
        member do
          delete 'crews/me', to: 'crews#destroy_me'
          delete 'request_to_joins', to: 'request_to_joins#destroy_by_canoe'
        end
        shallow do
          resources :discussions, except: :destroy do
            get 'decision_histories', on: :member
            resources :opinions
            resources :proposals do
              member do
                post :in_favor, to: 'votes#in_favor'
                post :opposed, to: 'votes#opposed'
                delete :unvote, to: 'votes#unvote'
              end
            end
          end
          resources :request_to_joins, only: [:create, :destroy] do
            patch :accept, on: :member
          end
          resources :invitations, only: [:create, :destroy]
        end
      end
    end
  end

  get '/:slug/discussions/:sequential_id', to: "discussions#short", as: 'short_discussion'
  get '/:slug', to: "canoes#short", as: 'short_canoe'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/devel/emails"
  end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  include CanoeTimestampable

  acts_as_paranoid
  acts_as_sequenced scope: :discussion_id

  belongs_to :user
  belongs_to :discussion, counter_cache: true
  has_one :canoe, through: :discussion
  has_many :attachments, as: :attachable
  has_many :votes do
    def by_crews
      self.where(user: proxy_association.owner.canoe.crews_as_user)
    end

    def by_guests
      self.where.not(user: proxy_association.owner.canoe.crews_as_user)
    end
  end
  has_many :in_favor_votes, -> { where choice: :in_favor }, class_name: Vote, counter_cache: 'in_favor_votes_count'

  validates :body, presence: true
  scope :latest, -> { order(id: :desc) }
  scope :order_by_in_favor_votes_count, -> { order(in_favor_votes_count: :desc) }
  scoped_search on: %w(body)

  accepts_nested_attributes_for :attachments

  def opposed_by? user
    voted_by?(user, :opposed)
  end

  def in_favor_by? user
    voted_by?(user, :in_favor)
  end

  def voted_by?(user, choice = nil)
    (choice.nil? ? votes : votes.with_choice(choice)).exists? user: user
  end

  def votes_count(choice)
    send(:"#{choice}_votes_count")
  end

  def best?(choice)
    discussion.proposals.top_of_votes_count(choice) == self.votes_count(choice)
  end

  def in_favor_percentage_by_crews
    votes.in_favor.by_crews.count.to_f / canoe.crews.count * 100
  end

  def timestamp_user
    self.user
  end
end

app/controllers/api/v1/proposals_controller.rb
class Api::V1::ProposalsController < Api::V1::BaseController
  include DiscussionActivityTraking

  def create
    @discussion = Discussion.find params[:discussion_id]
    @canoe = @discussion.canoe

    assert_crew!

    @proposal = @discussion.proposals.build(proposal_params)
    @proposal.user = current_user
    @proposal.attachments.each do |attachment|
      attachment.user = current_user
    end
    if @proposal.save
      create_porposals_create_activty(@proposal)
      push_to_client(@proposal)
      expose @proposal
    else
      error!(:invalid_resource, @proposal.errors)
    end
  end

  def update
    @proposal = Proposal.find params[:id]

    assert_current_user!(@proposal.user)

    if @proposal.update_attributes(proposal_params)
      push_to_client(@proposal)
      expose @proposal
    else
      error!(:invalid_resource, @proposal.errors)
    end
  end

  def destroy
    @proposal = Proposal.find params[:id]

    assert_current_user!(@proposal.user)

    if @proposal.destroy
      create_porposals_destroy_activty @proposal
      head :ok
    else
      error!(:invalid_resource, @proposal.errors)
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:body, attachments_attributes: [ :source ])
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  include SlackPushing
  include DiscussionActivityTraking

  before_filter :authenticate_user!, except: [:show]
  load_and_authorize_resource :canoe
  load_and_authorize_resource :discussion, through: :canoe, shallow: true
  load_and_authorize_resource :proposal, through: :discussion, shallow: true

  def show
  end

  def new
  end

  def edit
  end

  def create
    @proposal.user = current_user
    @proposal.attachments.each do |attachment|
      attachment.user = current_user
    end
    if @proposal.save
      create_porposals_create_activty(@proposal)
      push_to_slack(@proposal)
    end
    redirect_to @discussion
  end

  def update
    if @proposal.update_attributes(proposal_params)
      push_to_slack(@proposal)
      create_porposals_update_activty(@proposal)
    end
    redirect_to @proposal.discussion
  end

  def destroy
    if @proposal.destroy
      create_porposals_destroy_activty(@proposal)
      push_to_slack(@proposal)
    end
    redirect_to @proposal.discussion
  end

  private

  def proposal_params
    params.require(:proposal).permit(:body, attachments_attributes: [ :source ])
  end
end

app/views/proposals/_form.html.haml
= form_for @proposal do |f|
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit '저장', class: 'btn btn-default'

app/views/proposals/_proposal.html.haml
%li.list-group-item[proposal]
  %a.anchor(id="proposal-#{proposal.sequential_id}")
  .row
    .col-xs-9
      %p
        - if proposal.best?(:in_favor)
          %span.label.label-warning(style='margin-right: 3px;')
            %i.fa.fa-heart
            베스트
        - if proposal.best?(:opposed)
          %span.label.label-danger(style='margin-right: 3px;')
            %i.fa.fa-ban
            워스트
      %strong
        .clearfix.proposal__body
          %span.label.label-default.pull-left(style='margin-right: 3px;')= proposal.sequential_id
          = smart_body(proposal.body, {data: { toggle: 'preview', 'embed-stage': "##{dom_id(proposal)} .proposal__body--embeded", 'image-stage': "##{dom_id(proposal)} .attachments--image" } })
        .proposal__body--embeded
        = render partial: 'attachments/collection', locals: { attachable: proposal }
      %p.text-muted
        %small
          = user_byline proposal.user
          = link_to "#proposal-#{proposal.sequential_id}", style: 'margin-left: 10px; color:#999999 !important;' do
            %i.fa.fa-clock-o
            = date_f proposal.created_at
          - if can? :update, proposal
            = link_to [:edit, proposal] do
              %i.fa.fa-edit
          - if can? :destroy, proposal
            = link_to proposal, method: :delete, data: { confirm: '정말 삭제하시겠습니까?'}  do
              %i.fa.fa-trash
          %button.btn-link
            = render partial: 'attachments/button', locals: { attachable: proposal }
    .col-xs-3
      .pull-right.text-center
        %div
          - if !user_signed_in? or !proposal.canoe.crew?(current_user)
            %button.btn.btn-success.btn-sm.disabled
              %i.fa.fa-heart
              좋아요
              = proposal.votes.by_crews.in_favor.count
          - elsif proposal.in_favor_by?(current_user)
            = link_to unvote_proposal_path(proposal), method: :delete, class: 'btn btn-sm btn-success' do
              %span.change-icon
                %i.fa.fa-heart
                %i.fa.fa-minus-circle
              좋아요
              = proposal.votes.by_crews.in_favor.count
          - else
            = link_to in_favor_proposal_path(proposal), method: :post, class: 'btn btn-sm btn-default' do
              %span.text-default
                %i.fa.fa-heart-o
              좋아요
              = proposal.votes.by_crews.in_favor.count
        %div(style="margin-top: 3px; font-size: 13px;")
          - if !user_signed_in? or !proposal.canoe.crew?(current_user)
            .text-danger
              %i.fa.fa-ban
              안돼요
              = proposal.votes.opposed.count
          - elsif proposal.voted_by?(current_user, :opposed)
            = link_to unvote_proposal_path(proposal), method: :delete, class: 'text-danger' do
              %span.change-icon
                %i.fa.fa-ban
                %i.fa.fa-minus-circle
              안돼요
              = proposal.votes.opposed.count
          - else
            = link_to opposed_proposal_path(proposal), method: :post, class: 'text-muted' do
              %span.text-default
                %i.fa.fa-ban
              안돼요
              = proposal.votes.opposed.count

        - if proposal.votes.any?
          %div(style="margin-top: 10px; font-size: 13px;")
            %a.text-muted(data-toggle="collapse" href="##{dom_id(proposal)}__result" aria-expanded="false")
              %i.fa.fa-angle-down
                결과

  .collapse(id="#{dom_id(proposal)}__result")
    %hr
    - if proposal.votes.in_favor.any?
      .result__in_favor(style='margin: 10px 0')
        .row
          .col-xs-12
            %strong.text-success
              %i.fa.fa-heart
              좋아요
        - if proposal.votes.by_crews.in_favor.any?
          .row
            .col-xs-5
              %i.fa.fa-user
              회원
              #{proposal.votes.by_crews.in_favor.count}명
              (#{number_to_percentage proposal.in_favor_percentage_by_crews, precision: 0})
            .col-xs-7
              - proposal.votes.by_crews.in_favor.map do |v|
                @#{v.user.nickname}
        - if proposal.votes.by_guests.in_favor.any?
          .row
            .col-xs-5
              %i.fa.fa-user-secret
              손님
              #{proposal.votes.by_guests.in_favor.count}명
            .col-xs-7
              - proposal.votes.by_guests.in_favor.map do |v|
                @#{v.user.nickname}
    - if proposal.votes.opposed.any?
      .result__opposed(style='margin: 10px 0')
        .row
          .col-xs-12
            %strong.text-danger
              %i.fa.fa-ban
              안돼요
        - if proposal.votes.by_crews.opposed.any?
          .row
            .col-xs-5
              %i.fa.fa-user
              회원
              #{proposal.votes.by_crews.opposed.count}명
            .col-xs-7
              - proposal.votes.by_crews.opposed.map do |v|
                @#{v.user.nickname}
        - if proposal.votes.by_guests.opposed.any?
          .row
            .col-xs-5
              %i.fa.fa-user-secret
              손님
              #{proposal.votes.by_guests.opposed.count}명
            .col-xs-7
              - proposal.votes.by_guests.opposed.map do |v|
                @#{v.user.nickname}

app/views/proposals/edit.html.haml
.container
  %h1 제안 수정
  = render 'form'